"$schema" = 'https://starship.rs/config-schema.json'

format = """[](rose)$sudo$os$username\
[](bg:pine fg:rose)\
$directory\
[](fg:pine bg:gold)\
$git_branch\
$git_status\
[](fg:gold bg:base)\
[](fg:base bg:iris)\
$python${custom.codon}$rust\
[](fg:iris)\
$fill\
[](fg:overlay)$time$battery[](fg:overlay)  \
$line_break$character\
$shell"""

right_format = ""

# Palettes RosePine moon/dawn
palette = 'rose-pine-moon'

[palettes.rose-pine]
base = '#191724'
surface = '#1f1d2e'
overlay = '#26233a'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight_low = '#21202e'
highlight_med = '#403d52'
highlight_high = '#524f67'

[palettes.rose-pine-moon]
base = '#232136'
surface = '#2a273f'
overlay = '#393552'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight_low = '#2a283e'
highlight_med = '#44415a'
highlight_high = '#56526e'

[palettes.rose-pine-dawn]
base = '#faf4ed'
surface = '#fffaf3'
overlay = '#f2e9e1'
muted = '#9893a5'
subtle = '#797593'
text = '#575279'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'
highlight_low = '#f4ede8'
highlight_med = '#dfdad9'
highlight_high = '#cecacd'

[fill]
symbol = '―'
style = 'overlay'
disabled = false

##
[sudo]
format = '[🌸 ]($style)'
style = 'bg:rose fg:overlay'
disabled = false

[os]
disabled = false
style = 'bg:rose fg:overlay'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:rose fg:overlay"
style_root = "bg:rose fg:overlay"
format = '[ $user ]($style)'

[directory]
style = "fg:overlay bg:pine"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

## git
[git_branch]
symbol = ""
style = "fg:overlay bg:gold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:overlay bg:gold"
format = '[ $all_status $ahead_behind ]($style)'

## languages
[python]
symbol = ""
style = 'fg:overlay bg:iris'
format = '[ $symbol $version ]($style)'

[custom.codon]
symbol = ""
command = "codon --version"
detect_extensions = ['codon']
style = 'fg:overlay bg:iris'
format = '[ $symbol $output ]($style)'

[rust]
symbol = ""
style = "fg:overlay bg:iris"
format = '[ $symbol $output ]($style)'

###
[time]
disabled = false
time_format = "%R"
style = 'fg:text bg:overlay'
format = '[  $time ]($style)'

[battery]
full_symbol = '󰁹'
empty_symbol = ''
charging_symbol = '󰂄'
discharging_symbol = '󰂀'
unknown_symbol = '󰂑'
format = '[ $symbol $percentage ]($style)'

[[battery.display]]
style = 'fg:text bg:overlay'
threshold = 100

[line_break]
disabled = false

###
[character]
disabled = true
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:love)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[shell]
zsh_indicator = '󰬡'
fish_indicator = '󰈺 '
nu_indicator = '󰰒'
# powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'text bold'
disabled = false
