default_stages:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: devenv --impure shell shellcheck-hook
        language: system
        types:
          - shell
      - id: actionlint
        name: actionlint
        entry: devenv --impure shell actionlint-hook
        language: system
        files: ^.github/workflows/
        types:
          - yaml
