# 現在の config schema の version
version: 1
# git 操作時に使う protocol。対応値: ssh, https
git_protocol: ssh
# issue / pull request などの作成時に gh が起動する editor。空なら環境変数を使う。
editor:
# どのタイミングで対話的 prompt を出すか。これは hostname で上書きできない global 設定。対応値: enabled, disabled
prompt: enabled
# editor ベースの対話的 prompting の優先設定。これは hostname で上書きできない global 設定。対応値: enabled, disabled
prefer_editor_prompt: disabled
# コマンド出力を送る pager プログラム。例: "less"。空なら環境変数を使う。pager を無効にするには "cat" を指定する。
pager:
# aliases で gh コマンドの別名を作れる
aliases:
  co: pr checkout
# HTTP 接続を送る unix socket の path。空なら HTTP traffic は net/http.DefaultTransport が扱う。
http_unix_socket:
# URL を開くときに gh が使う web browser。空なら環境変数を使う。
browser:
# truecolor 対応 terminal で label を RGB hex color code で表示するか。対応値: enabled, disabled
color_labels: disabled
# カスタマイズ可能な 4-bit accessible colors を使うか。対応値: enabled, disabled
accessible_colors: disabled
# accessible な prompter を使うか。対応値: enabled, disabled
accessible_prompter: disabled
# 進捗表示としてアニメーション spinner を使うか。無効ならテキストの進捗表示を使う。対応値: enabled, disabled
spinner: enabled
