theme = "rose-pine-moon"
option-as-alt = "both"

[adaptive-theme]
light = "rose-pine-dawn"
dark = "rose-pine-moon"

[editor]
program = "nvim"
args = []

[window]
opacity = 0.8
blur = true
decorations = "Transparent"

[fonts]
size = 14
line-height = 1.2
family = "PlemolJP35 Console NF"
use-drawable-chars = true

[navigation]
mode = "Bookmark"
use-split = true
